### ISSUE TITLE
BUG: `file_format` is None

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#1032]
**Describe the bug**
After instantiation, `inst.file_format` and `inst.files.file_format` are `None`. 

**To Reproduce**
```
import pysat
euv = pysat.Instrument('icon', 'euv')
euv.file_format
euv.files.file_format
```
This doesn't update after refreshing the file list or loading a file.

**Expected behavior**
Should give me some info about the file time. At a minimum, file type (netCDF4, cdf).  Ideally, the full filename standard.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - Mac OS X Big SUr
 - Python 3.8.11

**Additional context**
Could be useful in pysatNASA unit tests to determine which instrument require extra testing instead of using skip statements based on file type after file download.

**Comment by rstoneback** [comment]
Current setup: `file_format` at the Instrument level is a template string that users may provide if the filenames they want to load differ from the standard filename construction (as encoded by the developers). The developer expected filename template is built into list_files and isn't stored anywhere. The `files.file_format` is the same thing, as transferred from the Instrument object at instantiation. `None` is the current expected value unless a user provides otherwise.

It could be possible to update things to store the template string actually used. This would be a breaking change.

**Comment by jklenzing** [comment]
OK, I see it now.  We should probably update the docstring to make this less confusing.  If we did attach the default file_format name to this parameter, would it actually be a breaking change? Or would it just use a different loop of code to do the same thing?

It looks like I can use `inst._list_files_rtn.keywords` to access the info I need for the testing problem, so no rush on this one.

**Comment by rstoneback** [comment]
It wouldn't break things if a developer attached the actual template string used in list_files to the Instrument object. Updating the standard to do these types of things is a 'breaking' change in that all the Instruments would have to be updated. Further, just doing it in list_files isn't consistent since list_files isn't always invoked at instantiation. A more consistent user experience with file_format would require assignment at instantiation, and this requires updating pysat and all the Instrument modules.

**Comment by rstoneback** [comment]
Solution: Improve the docstring for this attribute, and perhaps others are confusing

**Comment by jklenzing** [comment]
Closing with merge of #1050
