### ISSUE TITLE
Provide better exposure for methods in pysat._files

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#336]
**Is your feature request related to a problem? Please describe.**
Users may not be aware of built in file methods that could make their lives easier when adding new instruments.

**Describe the solution you'd like**
rename pysat._files.py to pysat.files.py

**Describe alternatives you've considered**

**Additional context**

**Comment by jklenzing** [comment]
I have a test branch up in #454.  The change is straightforward and works, but rapidly becomes confusing to me due to the existence of the `pysat.Files` class and the methods under `pysat.files`, which also contains the `Files` class.

Possible routes:
- move the methods to `pysat.utils.files` and leave the main class file hidden.
- break these apart at the top level with a rename of one or the other

**Comment by rstoneback** [comment]
Moving the relevant methods to pysat.utils.files sounds like a good plan to me.

**Comment by jklenzing** [comment]
OK.  I'll start mocking up a replacement PR. This will require deprecation warnings.

**Comment by jklenzing** [comment]
Looking over the code, it looks like `from_os` should really be moved from the class to `utils.files` as well.  Thoughts?

**Comment by rstoneback** [comment]
That’s a class method. It has to be defined within the Files class.

**Comment by jklenzing** [comment]
Closing with merge of #505
