### ISSUE TITLE
BUG: NASA Download

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#426]
**Describe the bug**

**To Reproduce**

omni = pysat.Instrument('omni', 'hro', '5min')

omni.download(dt.datetime(2001,1,1), dt.datetime(2010,1,1))

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-43-fddf6057a83d> in <module>()
----> 1 omni.download(dt.datetime(2001,1,1), dt.datetime(2010,1,1))

/Users/russellstoneback/Code/pysat/pysat/_instrument.py in download(self, start, stop, freq, user, password, date_array, **kwargs)
   1577                                sat_id=self.sat_id,
   1578                                data_path=self.files.data_path,
-> 1579                                **kwargs)
   1580         else:
   1581             self._download_rtn(date_array,

/Users/russellstoneback/Code/pysat/pysat/instruments/methods/nasa_cdaweb.py in download(supported_tags, date_array, tag, sat_id, remote_site, data_path, user, password, fake_daily_files_from_monthly, multi_file_day)
    287             except requests.exceptions.RequestException as exception:
    288                 logger.info(' '.join((exception, '- File not available for',
--> 289                                       date.strftime('%d %B %Y'))))
    290 
    291         else:

TypeError: sequence item 0: expected string, ConnectionError found

**Expected behavior**
Data download for full timeframe. I did get data from January through September.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.3
 - Version Python 2.7, pysat develop
 
**Additional context**

**Comment by jklenzing** [comment]
Tested this out for python 3.7 for both develop and develop-3.  Seeing the same error.

**Comment by jklenzing** [comment]
OMNI is one of our monthly files, which means the code tries to download a daily files but skips over the ones that don't exist.  Also seeing this error for the de2_rpa, which is daily but has a multi-month gap between Nov 1981 and Feb 1982.  

Further up the error message chain, I see
```
ConnectionError: HTTPSConnectionPool(host='cdaweb.gsfc.nasa.gov', port=443): 
Max retries exceeded with url: /pub/data/de/de2/plasma_rpa/ion2s_cdaweb/1982/de2_ion2s_rpa_19820110_v01.cdf 
(Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1a1e319908>: 
Failed to establish a new connection: [Errno 61] Connection refused'))
```
I suspect that the server is rejecting these because the requests are happening too frequently.  Putting a `time.sleep(1)` statement in the loop makes this problem go away, but does slow down the code for getting a lot of data.  Definitely not a long term solution.

Possible solutions:
- Use the `remote_files_list` method to get file list beforehand rather than blindly iterating.
- Only request first of month for monthly files
- Adding a wait statement only if data is not present (just after the logger statement)

**Comment by jklenzing** [comment]
Plan moving forward: 
- [ ] update cdaweb `list_remote_files` method to be consistent with start, stop dates
- [ ] Make sure new variables are passed through in _instrument class.
- [ ] use this method as part of download for cdaweb files (similar to how this is implemented for multi_file_day data)

**Comment by jklenzing** [comment]
To properly fix this bug, I need to create breaking changes in both `remote_file_list` and `remote_date_change`.

Proposed route forward:
- 2.2.0
  - [ ] Use `remote_file_list` to obtain available files for non-`multi_file` days. (solves documented omni and de2 problems)
  - [ ] Include update to warning message should this appear elsewhere suggesting that users restrict their download (good practice)
  - [ ] unit tests on the warning
- 3.0.0 (new issue?)
  - BREAKING CHANGE: use `start` and `stop` datetimes to specify a range for this method rather than `month`, `day`, `year`.  Improved compatibility with `download`, consistency with madrigal methods, cleaner code in .
  - Use same code sequence for both multi-file and single-file days
  - Re-evaluate naming conventions, ie, `remote_file_list` and `list_remote_file` for clarity and consistency.

@rstoneback? @aburrell?

**Comment by jklenzing** [comment]
Changes for 3.0 version pushed out to #436.

**Comment by jklenzing** [comment]
Closing with merge of #434
