### ISSUE TITLE
ENH: suggested changes for generate_instrument_list

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#518]
**Describe the issue**
Documents for and scope of `pysat.tests.instrument_test_class.generate_instrument_list`

1. The parameter variable name and some of the surrounding text are confusing, suggesting that the package name should be used as input instead of the instrument module within the package.  
2. The function is useful, and if included at a higher level (utils?) would partially address issue #67 

**Suggested Changes**

1a. Change parameter variable `package` to `inst_module`
1b. Change parameter description to `The instrument module within the package; e.g., pysat.instruments`.
1c. Add note saying the package should be imported first
1d. Change testing note to say something like `When used for unit/integration tests, should only be run once per instrument library.`
2a. Move to an outward facing module
2b. Change 'names' key to 'platforms', and have the values in there be a dict of lists:

Current behaviour after running `generate_instrument_list(pysat.instruments)`:
```
{'names': ['pysat_testing',
  'pysat_testing_xarray',
  'pysat_testing2d',
  'pysat_testing2d_xarray',
  'pysat_testmodel'],
 'download': [<pysat._instrument.Instrument at 0x11dd43210>,
  <pysat._instrument.Instrument at 0x11e68a4d0>,
  <pysat._instrument.Instrument at 0x11e988ad0>,
  <pysat._instrument.Instrument at 0x11e988850>,
  <pysat._instrument.Instrument at 0x11e9996d0>,
  <pysat._instrument.Instrument at 0x11e999a90>],
 'no_download': [<pysat._instrument.Instrument at 0x11e98d190>]}
```

Suggested behaviour:
```
{'platforms': {'pysat': ['testing', 'testing_xarray', 'testing2d', 'testing2d_xarray', 'testmodel']},
 'download': [<pysat._instrument.Instrument at 0x11dd43210>,
  <pysat._instrument.Instrument at 0x11e68a4d0>,
  <pysat._instrument.Instrument at 0x11e988ad0>,
  <pysat._instrument.Instrument at 0x11e988850>,
  <pysat._instrument.Instrument at 0x11e9996d0>,
  <pysat._instrument.Instrument at 0x11e999a90>],
 'no_download': [<pysat._instrument.Instrument at 0x11e98d190>]}
```

This would require a small amount of reconstruction in the tests, but would be more consistent with the use of the keywords `platform` and `name`.

**Comment by rstoneback** [comment]
Is the current method sensitive to the ordering of methods? How do you know which download and no download go with the names? Particularly if there is a travis skip option? In this case the length of download and no_download combined don't add up to the length of names. 


How about keying on platform and then name?
 ```
 {'pysat': {'testing': {'download': True, method: <pysat._instrument.Instrument at 0x11dd43210>},
           {'testing_xarray': {'download': True, method: <pysat._instrument.Instrument at 0x11e68a4d0>},
           {'test_model': {'download': False, method: <pysat._instrument.Instrument at 0x11e988ad0>}}}
```

I'm also in favor of having the list of supported platforms and names code shifted to a public module.

**Comment by jklenzing** [comment]
Currently, the list is generated based on the `__all__` property of the instrument library and the test flags for each module.  The instrument lists for download and no_download are not particularly clear in this format as the info is hidden in the instrument object at this level.  Note that each instrument object represents a particular combination of tag and sat_id, which means that the sum of the two instrument lists should be longer than the list of modules.  In the above case, we test for three different tags under `pysat_testing`, 2 with download, 1 with no_download.  The travis flags mean that the lists will be sorted differently due to ftp access.

While looking into this, I noticed another bug/feature in the current tests:  Each module is tested to ensure a `_test_date` object is there, but not that it exists for all tags.  So we only test if a tag/sat_id has a test_date, which is a hole in the testing not documented by the current writeups.

**Comment by rstoneback** [comment]
Thanks for the clarification on the structure and the reminder the objects are the Instrument objects, not the download method as I was first thinking for some reason.

**Comment by jklenzing** [comment]
Some thoughts on the proposal
- How about `inst_library` instead of `package`?  `inst_module` is used elsewhere to define a single instrument module.
- I prefer loading by `inst_module` (pysat_testing) in the tests rather than `platform` and `name` keywords, as this does not assume you have registered modules from other libraries when running the tests or require you to register them.  This may be a minor issue in the end, but it does keep the tests from altering a user's setup.
- I like the idea of combining this with #67, but that issue requires full access to the registry, and the tests should be compartmentalized.  There should be a way of pulling out the common functionality as a public module

**Comment by jklenzing** [comment]
Plan forward
- [ ] Use dict to store instrument objects
- [ ] remove try / except statements in testing class
- [ ] rename `package` as `inst_loc`

**Comment by jklenzing** [comment]
Closing with merge of #552
