### ISSUE TITLE
BUG: change in registry behaviour

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#549]
**Describe the bug**
The new registry behaviour causes pysat to fail in a less-than-informative manner

**To Reproduce**
```import pysat

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-865d297c82ea> in <module>
----> 1 import pysat

~/Programs/Git/pysat/pysat/__init__.py in <module>
     97                     line = line.strip()
     98                     # stored as platform, name, module string
---> 99                     platform, name, inst_module = line.split(' ')
    100                     # dict of dicts, keyed by platform then name
    101                     if platform not in user_modules:

ValueError: not enough values to unpack (expected 3, got 1)
```

**Expected behavior**
I would expect pysat to tell me that I need to delete my old registry file and re-import my registered modules.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX Mojave
 - Version Python 3.7
 - Other details about your setup that could be relevant: working on develop-3

**Additional context**
This may not be an issue if the error doesn't come up if you're set up for pysat 2+ and then change to 3+ without triggering the problem.

**Comment by jklenzing** [comment]
Yeah, I ran into this too.  Is a simple warning enough?  Should we include a `reset` function in the registry to remove the file if users don't want to hunt down their config settings?

**Comment by rstoneback** [comment]
The registry hasn't been in a release version yet. Only those running develop-3 that registered a package with the old code will run into it. I did put a warning in the new registry pull but I could’ve been more pro-active. I’ll remember for next time.

In this case I don’t think an optional reset would work since the failure happens upon import. An automatic translator could be implemented. My guess is the impacted user base is probably small and since the old registry is dead, long live the new registry, won’t be growing.

**Comment by aburrell** [comment]
> The registry hasn't been in a release version yet.

Great!  Then I think we can close this issue.  If anyone else things should be a bit more bullet-proof we can open it back up.
