### ISSUE TITLE
`pysat.utils.registry.register_by_module` doesn't work.

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#550]
**Describe the bug**
`pysat.utils.registry.register_by_module` doesn't seem to work.

**To Reproduce**
```
import pysat
import pysatNASA

# This will fail regardless, because it should specify the instrument module
pysat.utils.registry.register_by_module(pysatNASA)                                                                 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-3c7313c62102> in <module>
----> 1 pysat.utils.registry.register_by_module(pysatNASA)

~/Programs/Git/pysat/pysat/utils/registry.py in register_by_module(module)
    256 
    257     # get a list of all user specified modules attached to module
--> 258     module_names = module.__all__
    259     # add in package preamble
    260     module_names = [module.__name__ + '.' + mod for mod in module_names]

AttributeError: module 'pysatNASA' has no attribute '__all__'
```
Trying the correct way:
```
pysat.utils.registry.register_by_module(pysatNASA.instruments)                                                     
pysat WARNING: Unable to find any files that match the supplied template. If you have the necessary files please check pysat settings and file locations (e.g. pysat.pysat_dir).
```
The WARNING is repeated many times, because there are many instruments that match the format.  Not sure why this one isn't working.

Trying Madrigal the correct way:
```
import pysatMadrigal
pysat.utils.registry.register_by_module(pysatMadrigal.instruments)

pysat WARNING: Unable to find any files that match the supplied template. If you have the necessary files please check pysat settings and file locations (e.g. pysat.pysat_dir).
WARNING:pysat:Unable to find any files that match the supplied template. If you have the necessary files please check pysat settings and file locations (e.g. pysat.pysat_dir).
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-7-129f1e66ac6b> in <module>
----> 1 pysat.utils.registry.register_by_module(pysatMadrigal.instruments)

~/Programs/Git/pysat/pysat/utils/registry.py in register_by_module(module)
    260     module_names = [module.__name__ + '.' + mod for mod in module_names]
    261     # register all of them
--> 262     register(module_names)
    263 
    264     return

~/Programs/Git/pysat/pysat/utils/registry.py in register(module_names, overwrite)
    176         validate.package.__name__ = '.'.join(pack_part)
    177         # run tests
--> 178         validate.test_modules_standard(mod_part)
    179         validate.test_standard_function_presence(mod_part)
    180 

~/Programs/Git/pysat/pysat/tests/instrument_test_class.py in test_modules_standard(self, name)
    152                 # Test the required class attributes
    153                 for iattr in self.inst_attrs:
--> 154                     assert hasattr(inst, iattr)
    155                     assert isinstance(getattr(inst, iattr),
    156                                       self.attr_types[iattr])

AssertionError: 

```

**Expected behavior**
I would expect this routine to work without an optional variable being supplied by the dependent routine.  Since this variable seems to be required, I would expect this to be in the pysat documentation.  I wasn't able to find this when I looked at the docs.

I would also expect the function to work in the second to instances.  The blank AssertionError may reflect something wrong in one of the Madrigal instruments, but not really sure what it is given the blankness.

**Desktop (please complete the following information):**
 - OS: OSX Mojave
 - Version 3.7
 - Other details about your setup that could be relevant: on develop-3 for pysat, main for pysatNASA, tec PR for pysatMadrigal

**Comment by aburrell** [comment]
More context
--------------
Despite saying it didn't work, it did work for (all?) of the NASA instruments.  I found this out after I ran the following code.  Not sure why it would fail like this when trying to register and existing module.

```
import pysat
pysat.utils.registry.register('pysatNASA.instruments.cnofs_ivm')    
                                              
pysat.utils.registry ERROR: There was a problem trying to import p
ERROR:pysat.utils.registry:There was a problem trying to import p
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-10-fd80167aec23> in <module>
----> 1 pysat.utils.registry.register('pysatNASA.instruments.cnofs_ivm')

~/Programs/Git/pysat/pysat/utils/registry.py in register(module_names, overwrite)
    152         # first, ensure module string directs to something importable
    153         try:
--> 154             inst_module = importlib.import_module(module_name)
    155         except Exception:
    156             # log then preserve trace and propagate error

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _gcd_import(name, package, level)

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _find_and_load(name, import_)

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'p'
```

**Comment by rstoneback** [comment]
Thanks for the report.

The warning isn't coming from the registry itself. My current guess (while on telecom) is the test calls I make to ensure the instrument module is compatible instantiate the instrument. The warning is the standard feedback whenever an instrument doesn’t find any files.

import pysatMadrigal
pysat.utils.registry.register_by_module(pysatMadrigal.instruments)

Is the intended use.



On Sep 16, 2020, at 1:30 PM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


More context

Despite saying it didn't work, it did work for (all?) of the NASA instruments. I found this out after I ran the following code. Not sure why it would fail like this when trying to register and existing module.

import pysat
pysat.utils.registry.register('pysatNASA.instruments.cnofs_ivm')

pysat.utils.registry ERROR: There was a problem trying to import p
ERROR:pysat.utils.registry:There was a problem trying to import p
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-10-fd80167aec23> in <module>
----> 1 pysat.utils.registry.register('pysatNASA.instruments.cnofs_ivm')

~/Programs/Git/pysat/pysat/utils/registry.py in register(module_names, overwrite)
    152         # first, ensure module string directs to something importable
    153         try:
--> 154             inst_module = importlib.import_module(module_name)
    155         except Exception:
    156             # log then preserve trace and propagate error

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128
    129

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _gcd_import(name, package, level)

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _find_and_load(name, import_)

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'p'

**Comment by rstoneback** [comment]
The send button got hit too early.

This output:

import pysatMadrigal
pysat.utils.registry.register_by_module(pysatMadrigal.instruments)

pysat WARNING: Unable to find any files that match the supplied template. If you have the necessary files please check pysat settings and file locations (e.g. pysat.pysat_dir).
WARNING:pysat:Unable to find any files that match the supplied template. If you have the necessary files please check pysat settings and file locations (e.g. pysat.pysat_dir).
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-7-129f1e66ac6b> in <module>
----> 1 pysat.utils.registry.register_by_module(pysatMadrigal.instruments)

~/Programs/Git/pysat/pysat/utils/registry.py in register_by_module(module)
    260     module_names = [module.__name__ + '.' + mod for mod in module_names]
    261     # register all of them
--> 262     register(module_names)
    263
    264     return

~/Programs/Git/pysat/pysat/utils/registry.py in register(module_names, overwrite)
    176         validate.package.__name__ = '.'.join(pack_part)
    177         # run tests
--> 178         validate.test_modules_standard(mod_part)
    179         validate.test_standard_function_presence(mod_part)
    180

~/Programs/Git/pysat/pysat/tests/instrument_test_class.py in test_modules_standard(self, name)
    152                 # Test the required class attributes
    153                 for iattr in self.inst_attrs:
--> 154                     assert hasattr(inst, iattr)
    155                     assert isinstance(getattr(inst, iattr),
    156                                       self.attr_types[iattr])

AssertionError:

Is coming up since one of the instrument modules is missing one its required attributes.

On Sep 16, 2020, at 1:36 PM, Russell Stoneback <rstoneba@utdallas.edu<mailto:rstoneba@utdallas.edu>> wrote:

Thanks for the report.

The warning isn't coming from the registry itself. My current guess (while on telecom) is the test calls I make to ensure the instrument module is compatible instantiate the instrument. The warning is the standard feedback whenever an instrument doesn’t find any files.

import pysatMadrigal
pysat.utils.registry.register_by_module(pysatMadrigal.instruments)

Is the intended use.



On Sep 16, 2020, at 1:30 PM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


More context

Despite saying it didn't work, it did work for (all?) of the NASA instruments. I found this out after I ran the following code. Not sure why it would fail like this when trying to register and existing module.

import pysat
pysat.utils.registry.register('pysatNASA.instruments.cnofs_ivm')

pysat.utils.registry ERROR: There was a problem trying to import p
ERROR:pysat.utils.registry:There was a problem trying to import p
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-10-fd80167aec23> in <module>
----> 1 pysat.utils.registry.register('pysatNASA.instruments.cnofs_ivm')

~/Programs/Git/pysat/pysat/utils/registry.py in register(module_names, overwrite)
    152         # first, ensure module string directs to something importable
    153         try:
--> 154             inst_module = importlib.import_module(module_name)
    155         except Exception:
    156             # log then preserve trace and propagate error

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128
    129

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _gcd_import(name, package, level)

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _find_and_load(name, import_)

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'p'

**Comment by rstoneback** [comment]
Expected behavior
I would expect this routine to work without an optional variable being supplied by the dependent routine. Since this variable seems to be required, I would expect this to be in the pysat documentation.

The use of __all__ is noted in the register_by_module docstring under Note.

**Comment by aburrell** [comment]
Documentation where we explain how to create a new instrument or new instrument module.

**Comment by rstoneback** [comment]
Right. Thanks for the clarification.

**Comment by rstoneback** [comment]
@rfuller81 Please take a look at the documentation aspects of this issue.

**Comment by rstoneback** [comment]
A pysat parameter was added that lets users control if they get warnings when a pysat.Instrument doesn't find any files. By default, the warning is turned off. Thus, for the original use case presented above the user should no longer get the unexpected warnings.
