### ISSUE TITLE
BUG/TST: instrument list update during local run of tests

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#627]
**Describe the bug**
Currently, all instrument tests will download a file to a temp directory so that the local instrument data files are not changed.  Two related bugs have been documented with this procedure.
1. If instrument tests successfully run, the user's file list for the instruments are updated to show only the test file.
2. If an instrument fails during download, and a user has other data files elsewhere, the list is not updated and the load tests are run, not skipped.  These too will fail, littering the error log with unnecessary info.

**To Reproduce**
1. Run instrument tests locally for a package (pysatNASA, etc) where you have data.
2. Afterward load a pysat instrument for that package.
3. `inst.files.files`
4.  Only the test file date appears

**Expected behavior**
Units tests should not alter local setups.

I think the correct solution is to use both `update_files=True` and `temporary_file_list=True` for each instrument instantiation in the tests.  This should refresh the files for each test, but not save to file.  @rstoneback, is this right?

**Comment by jklenzing** [comment]
Closing with merge of #630

**Comment by rstoneback** [comment]
Just saw this :P Sorry about that.

Though things are already closed and compete, yes, the listed flags are the way to go.

Cheers,
Russell

On Dec 15, 2020, at 9:09 AM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:



Describe the bug
Currently, all instrument tests will download a file to a temp directory so that the local instrument data files are not changed. Two related bugs have been documented with this procedure.

  1.  If instrument tests successfully run, the user's file list for the instruments are updated to show only the test file.
  2.  If an instrument fails during download, and a user has other data files elsewhere, the list is not updated and the load tests are run, not skipped. These too will fail, littering the error log with unnecessary info.

To Reproduce
Steps to reproduce the behavior:

  1.  Run instrument tests locally for a package (pysatNASA, etc) where you have data.
  2.  Afterward load a pysat instrument for that package.
  3.  inst.files.files
  4.  Only the test file date appears

Expected behavior
Units tests should not alter local setups.

I think the correct solution is to use both update_files=True and temporary_file_list=True for each instrument instantiation in the tests. This should refresh the files for each test, but not save to file. @rstoneback<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frstoneback&data=04%7C01%7Crstoneba%40utdallas.edu%7C36f58e5b75e04f8643a508d8a10b5fe8%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637436417519887441%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HIBbFNkmiXEIZJWXNwYky9pICe8mEQ7xj9BWjgRjHyE%3D&reserved=0>, is this right?
