### ISSUE TITLE
Remove support for `children` in Meta

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#789]
**Is your feature request related to a problem? Please describe.**
Support for children was added since multi-dimensional data originally required DataFrames within DataFrames. One variable label could have multiple variables stored within. pysat now supports xarray and this variable within variables issue should no longer exist.

**Describe the solution you'd like**
Add a DeprecationWarning.... and then remove support in the future.

**Describe alternatives you've considered**
Leave as is.

**Additional context**

**Comment by jklenzing** [comment]
Deprecation in 3.1.0

**Comment by jklenzing** [comment]
@rstoneback, are the 2D pandas objects being deprecated as well?  Or are we just changing how the meta is treated?

**Comment by rstoneback** [comment]
You mean the DataFrames within DataFrames? Yes, deprecated. We shouldn’t be using that going forward.

**Comment by jklenzing** [comment]
Proposal for next pysat meeting: We continue with meta children deprecation in 3.1.0, and push off other meta upgrades to 3.2.0 (when we remove the meta children).  This should make most of the rewrites simpler, since we won't have to deal with the higher order meta objects.

Issues potentially affected: #661, #767, #786, #900, #911
Pulls potentially affected: #896
